In [3]:
import pandas as pd

mom = pd.read_parquet("../data/processed/us_momentum_12_1.parquet")
rets = pd.read_parquet("../data/processed/us_monthly_returns.parquet")

display(mom.info())
display(rets.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Empty DataFrame

None

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Empty DataFrame

None

In [4]:
raw = pd.read_parquet("../data/raw/us_prices_daily.parquet")
display(raw.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Empty DataFrame

None

In [30]:
import sys
sys.path.append("../src")
from cross_sectional_utils import build_deciles

raw = pd.read_parquet("../data/raw/us_prices_daily.parquet")
# print(raw.shape)
rets = pd.read_parquet("../data/processed/us_monthly_returns.parquet")
# display(ret.info())
mom = pd.read_parquet("../data/processed/us_momentum_12_1.parquet")
# display(mom.info())
# ret.describe().T[["count", "mean", "std"]].head()
print(mom.std(axis=1).mean())
print(rets.std(axis=1).mean())
wml = build_deciles(mom, rets)
print(wml.min(), wml.quantile(0.01), wml.median(), wml.quantile(0.99), wml.max())
print("wml mean:", wml.mean())

0.7575799209235201
0.7780554717598138
-0.39451780712959567 -0.20549464303313295 0.016986699093058208 0.15625439443816727 0.21016690622917636
wml mean: 0.010778772149812866

In [29]:
display(wml.info())
display(mom.dropna().head(10))
display(rets.head(10))

<class 'pandas.core.series.Series'>
RangeIndex: 300 entries, 0 to 299
Series name: None
Non-Null Count  Dtype
--------------  -----
300 non-null    float64
dtypes: float64(1)
memory usage: 2.5 KB

None

Ticker,RAFE,INSE,VIVS,XVV,DEA,VCEL,NOAH,TIPZ,CPSS,TMUS,...,HOLX,SCHE,MID,NHPAP,GRI,NUWE,OXBR,IPO,XLI,NWFL
Date,,,,,,,,,,,,,,,,,,,,,
2022-03-31,0.198737,0.563636,-0.755294,0.193579,0.002424,-0.263049,-0.297763,0.052420,1.848558,-0.098358,...,-0.025662,-0.041174,-0.085202,0.085248,-0.201309,-0.840000,0.805461,-0.303638,0.126594,0.133418
2022-04-30,0.081766,0.551130,-0.630705,0.106467,0.042500,-0.258146,-0.361261,0.063736,1.920595,-0.016602,...,-0.043157,-0.068719,-0.031413,0.072773,0.592672,-0.832487,1.335968,-0.262142,0.024975,0.099973
2022-05-31,0.064277,0.490909,-0.559719,0.086474,0.036809,-0.387696,-0.465834,0.024716,1.335632,-0.028608,...,0.171930,-0.114255,-0.039168,0.063470,-0.560748,-0.794297,1.707921,-0.292683,0.024001,0.156296
2022-06-30,-0.032094,-0.189354,-0.694681,-0.022496,-0.046683,-0.495575,-0.605748,-0.010811,1.446352,-0.129445,...,0.141611,-0.176535,-0.143095,0.056188,-0.690000,-0.803483,1.047826,-0.421583,-0.082667,0.147987
2022-07-31,-0.009321,-0.137255,-0.743617,-0.048980,-0.019952,-0.482857,-0.611017,-0.028468,2.008889,-0.079680,...,0.128147,-0.179715,-0.234498,0.014896,-0.895221,-0.857143,0.984733,-0.530362,-0.065610,0.052666
2022-08-31,-0.099236,-0.257118,-0.769231,-0.148848,-0.117248,-0.524367,-0.475907,-0.088131,1.062374,-0.065824,...,-0.076493,-0.157312,-0.334761,0.076999,-0.860566,-0.854321,-0.127937,-0.520159,-0.142486,-0.004093
2022-09-30,-0.065463,-0.187745,-0.616188,-0.098069,-0.013527,-0.399298,-0.553617,-0.041338,1.241259,0.044081,...,-0.098168,-0.184703,-0.247448,0.052129,-0.943101,-0.861386,0.087227,-0.512345,-0.071328,0.062187
2022-10-31,-0.063290,-0.105128,-0.652941,-0.093901,-0.083522,-0.488729,-0.523027,-0.059857,1.006897,0.126800,...,-0.084677,-0.159581,-0.225932,0.027021,-0.943604,-0.336364,-0.084746,-0.500855,-0.039229,0.042161
2022-11-30,-0.193252,-0.357818,-0.669887,-0.233240,-0.208993,-0.495871,-0.689250,-0.136496,0.113323,0.166391,...,-0.119902,-0.257460,-0.350013,-0.051076,-0.940126,-0.741627,-0.354545,-0.585764,-0.194214,0.047750
2022-12-31,-0.093010,-0.205586,-0.657620,-0.175317,-0.135966,-0.277614,-0.639857,-0.131976,-0.171613,0.392887,...,-0.092734,-0.255651,-0.287645,-0.084297,-0.953748,-0.830189,-0.536697,-0.555996,-0.048377,0.149091

Ticker,RAFE,INSE,VIVS,XVV,DEA,VCEL,NOAH,TIPZ,CPSS,TMUS,...,HOLX,SCHE,MID,NHPAP,GRI,NUWE,OXBR,IPO,XLI,NWFL
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-02-29,NaN,NaN,NaN,NaN,NaN,1.463415,NaN,NaN,0.061224,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.055172,-0.052960
2000-03-31,NaN,NaN,NaN,NaN,NaN,0.346535,NaN,NaN,0.153846,NaN,...,0.154545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.139207,0.039474
2000-04-30,NaN,NaN,NaN,NaN,NaN,-0.323529,NaN,NaN,-0.333333,NaN,...,-0.015748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.014446,-0.016633
2000-05-31,NaN,NaN,NaN,NaN,NaN,-0.086957,NaN,NaN,-0.200000,NaN,...,-0.256000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.004219,-0.045455
2000-06-30,NaN,NaN,NaN,NaN,NaN,-0.083333,NaN,NaN,0.031250,NaN,...,0.161290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.039331,0.006803
2000-07-31,NaN,NaN,NaN,NaN,NaN,-0.285714,NaN,NaN,0.454545,NaN,...,0.111111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.015470,0.067568
2000-08-31,NaN,NaN,NaN,NaN,NaN,0.945455,NaN,NaN,0.166667,NaN,...,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.099021,0.044304
2000-09-30,NaN,NaN,NaN,NaN,NaN,-0.158879,NaN,NaN,-0.035714,NaN,...,-0.118519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.029042,-0.048485
2000-10-31,NaN,NaN,NaN,NaN,NaN,-0.311111,NaN,NaN,0.037037,NaN,...,-0.109244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.022495,0.002313

In [27]:
wml_2000_2009 = wml[:120].mean()
wml_2010_2019 = wml[120:240].mean()
wml_2020 = wml[240:].mean()

print(wml_2000_2009, wml_2010_2019, wml_2020)

-0.008041746935054708 0.013501621264920886 0.026936079279182935